### ISSUE TITLE
Change the text for each guide in response to !make

### ISSUE THREAD

**Issue by tannewt** [tandpfun/MakerSandbot#1]
Instead of the bot saying "Click for your *random* guide" it could say something like "Click to make a LED tiara."

This could be done by storing another string with every guide url that describes what it makes. Then, when determining a random guide, it would also send the specific text for it.

Related code is here I think:
https://github.com/tandpfun/MakerSandbot/blob/master/bot.js#L315

**Comment by tandpfun** [comment]
Added!
